### ISSUE TITLE
Merchant gets 403 Forbidden error when selecting Oxipay

### ISSUE THREAD

**Issue by blueninja2** [oxipay/oxipay-woocommerce#40]
**1 -** Erik at Buy Anime Aus is getting a 403 Forbidden error message when using the latest version of Oxipay - screenshot below.

**2 -** At the very bottom is the URL that we get in the address bar (seems to be attempting to connect to Oxipay but can't).

**3 -** At the bottom of the error page, there is a link to another page [Troubleshooting 403 Errors](http://support.hostgator.com/articles/employees/403-forbidden-or-no-permission-to-access?utm_source=externalerror&utm_medium=hgsuspage&utm_campaign=client403) which indicates that the issue might be happening because of file permissions / .htaccess error.

**4-** Merchant contacted hosting company who suggested that the problem was because the plugin was using brute force when accessing web server:

---
![image](https://cloud.githubusercontent.com/assets/22509613/24128268/ad36f262-0e2a-11e7-9bf7-b544eefa14f1.png)

---

![image](https://cloud.githubusercontent.com/assets/22509613/23983773/d98c9aba-0a65-11e7-8d45-417df890c2da.png)

---

`
https://www.buyanimeaus.com.au/wp-content/plugins/Oxipay/processing.php?x_reference=2365&x_account_id=41100542&x_amount=868.95&x_currency=AUD&x_url_callback=https%3A%2F%2Fwww.buyanimeaus.com.au%2Fwp-content%2Fplugins%2FOxipay%2Fcallback.php&x_url_complete=https%3A%2F%2Fwww.buyanimeaus.com.au%2Fcheckout%2Forder-received%2F2365%3Fkey%3Dwc_order_58ca1d7b82538&x_url_cancel=https%3A%2F%2Fwww.buyanimeaus.com.au%2Fcart%2F%3Fcancel_order%3Dtrue%26order%3Dwc_order_58ca1d7b82538%26order_id%3D2365%26redirect&x_test=no&x_shop_country=AU&x_shop_name=Buy+Anime+Aus&x_customer_first_name=Sam&x_customer_last_name=Al-Khalfa&x_customer_email=sam.al-khalfa%40certegy.com.au&x_customer_phone=0407229128&x_customer_billing_country=AU&x_customer_billing_city=Adelaide&x_customer_billing_address1=97+Pirie+St&x_customer_billing_address2=&x_customer_billing_state=SA&x_customer_billing_zip=5095&x_customer_shipping_country=AU&x_customer_shipping_city=&x_customer_shipping_address1=&x_customer_shipping_address2=&x_customer_shipping_state=&x_customer_shipping_zip=&gateway_url=https%3A%2F%2Fsecure.oxipay.com.au%2FCheckout%3Fplatform%3DWooCommerce&x_signature=ff74f1850069bcaa919ed99968c73d293284dbc4ce487204bc01308b76c1ae83
`

**Comment by jmcmanamey-terem** [comment]
We have attempted to reach out the merchant this morning via both phone and email. Waiting on a response. The approach is to set up a remote assistance session to understand why he is having problems with his web hosting platform.

**Comment by esteban-terem** [comment]
After having a remote support session with the merchant, could be determined that the cause of the issue is a default Hostgator Apache mod_security configuration that prevents the use of unencoded URLs to external hosts as parameters.

Example:
https://www.buyanimeaus.com.au/?xxx=http://yyy.zzz returns 403.

This can be fixed raising a support ticket to Hostgator for the use of of unencoded URLs to external hosts as parameters to be whitelisted in Apache's mod_security.

Reference:
http://forums.hostgator.com/apache-upgrade-broke-feature-wordpress-t40603.html

A long-term fix/enhancement is encode the URLs in Base64 as described in enhancement #49.

**Comment by jmcmanamey-terem** [comment]
@blueninja2 We've spoken to the merchant on your behalf and asked them to raise a request to their hosting provider for the workaround.

**Comment by blueninja2** [comment]
Issue has been resolved.
