### ISSUE TITLE
Test simplification

### ISSUE THREAD

**Issue by esteban-terem** [oxipay/oxipay-woocommerce#44]
Single payment gateway URL and no visible test mode flag.

Update the plugin configuration screen to show a single payment gateway URL and no visible test mode flag. If the merchant/integrator wants to point their website at the production payment gateway they’d configure the payment gateway URL to be a production URL (i.e. secure.oxipay). If they want to point their website at an integration/sandbox URL, they’d configure the payment gateway URL to be a sandbox URL (i.e. securesandbox.oxipay).

Also, remove the test mode checkbox, however, because our request API is based on Shopify, which has a test flag, we should still send this through to the payment gateway hardcoded as false

**Comment by blueninja2** [comment]
Tested and passed.
