### ISSUE TITLE
Encode URL parameters that contain URL values in Base64 to prevent 403 security errors

### ISSUE THREAD

**Issue by esteban-terem** [oxipay/oxipay-woocommerce#49]
The Hostgator hosting provider enables by default an Apache mod_security rule that prevents the use of unencoded URLs to external hosts as parameters (#40 issue).

For example, although this URL can be accessed OK (HTTP 200 OK)
https://www.hostgator_hosted_domain.com.au/wp-content/plugins/Oxipay/processing.php

This one results in a HTTP 403 response
https://www.hostgator_hosted_domain.com.au/wp-content/plugins/Oxipay/processing.php?gateway_url=https%3A%2F%2Fsecure.oxipay.com.au%2FCheckout%3Fplatform%3DWooCommerce

This is due to the presence of the gateway_url parameter which value is an unencoded URL to an external domain (https://secure.oxipay.com.au/...).

An anhancement is proposed to encode this URL values in Base64 before sending them to Oxipay. This requires the backend server to decode them.

**Comment by esteban-terem** [comment]
References:
* http://forums.hostgator.com/apache-upgrade-broke-feature-wordpress-t40603.html
* https://core.trac.wordpress.org/ticket/16940
* https://nextsoftwaresolutions.zendesk.com/hc/en-us/articles/201764425-403-Forbidden-error-in-xAPI-Content-page-on-HostGator-and-similar-hosts

**Comment by am-oxipay** [comment]
This is no longer an issue due to the process being changed to initiate this via javascript. there is no redirect occurring
