### ISSUE TITLE
[QAIT] Shopping cart not cleared for successful orders

### ISSUE THREAD

**Issue by Piyush-Qait** [oxipay/oxipay-woocommerce#52]
Steps to Replicate:

1) Launch the URL: http://115.113.54.81/wordpress/?v=a6cd7f0b74bc
2) Click on shop
3) Click on any product and then click on ‘Add to Cart’
4) Click on Proceed to checkout
5) Enter your billing details
6) Select Oxipay in payment options and click on ‘Proceed to Oxipay’
7) Login with valid credentials on Oxipay
8) Enter in card details and click on ‘Confirm’ button
9) Verify the result on wordpress

Actual Result: Shopping Cart does not get empty on wordpress when payment is successful in Oxipay

Acceptance Criteria : Application should empty the cart on wordpress when the payment is successful in Oxipay

Screencast: https://www.screencast.com/t/4naGgplEFKE

Test Case: Verify that when payment is successful in Oxipay, active cart becomes empty

Shared Document: http://docs.oxipay.com.au/platforms/magento_1/

oxipay-woocommerce_v1.0.0
WordPress-4.7.4
Woocommerce-3.0.4

**Comment by blueninja2** [comment]
We suspect the issue is caused by issue #57 to do with Permalinks not being configured correctly. 

I'll leave this issue open until defect 57 is addressed after which we will revisit this issue.
