### ISSUE TITLE
[QAIT]Oxipay payment gateway> Application does not displays correct merchant name as configured from Oxipay plugin setting.

### ISSUE THREAD

**Issue by Piyush-Qait** [oxipay/oxipay-woocommerce#53]
**Prerequisite**: Setup ‘Shop Name’ from admin.

**Steps to Replicate:**
1) Launch the URL: http://115.113.54.81/wordpress
2) Click on shop
3) Click on any product and then click on ‘Add to Cart’
4) Click on Proceed to checkout
5) Enter your billing details
6) Select Oxipay in payment options and click on ‘Proceed to Oxipay’
7) Verify the result

**Acceptance Criteria:** System should display same shop name as configured from Oxipay settings in admin.

**Screen Cast:** https://www.screencast.com/t/oydnjbpU6 

**Shared Document:** http://docs.oxipay.com.au/platforms/woocommerce/

**Test Case :**
#44 - "Verify that application displays the shop name on Oxipay platform which is configured from admin"

Ubuntu: 16.04 LTS
PHP version: PHP 5.6.30
mysql Ver: 14.14
Apache: 2.4.18
oxipay-woocommerce_v1.0.0
WordPress-4.7.4
Woocommerce-3.0.4

**Comment by blueninja2** [comment]
Hi Raman,
This is not a defect with Oxipay as the Oxipay application is displaying the merchant's name that is set in the database.

**Comment by blueninja2** [comment]
Clarify with QA infot ech that the name is being picked up from the database not the plugin. Sam/Tao to clarify this on the docs website as well.

**Comment by am-oxipay** [comment]
I believe this has been resolved.
