### ISSUE TITLE
[QAIT]Order status is displaying as 'Pending Payment' at admin end.

### ISSUE THREAD

**Issue by Piyush-Qait** [oxipay/oxipay-woocommerce#54]
Steps to Replicate:

1) Launch the Magento URL: http://115.113.54.81/wordpress 
2) Add a product to cart & checkout using OXIPAY.
3) Now launch the admin dashboard 'http://115.113.54.81/wordpress/wp-admin' and login with valid credentials says "ramanjeetsingh@qainfotech.com / YHK6MsIfEhM*xEb5hg".
4) Now navigate to WooCommerce> Orders.
5) Verify

Actual Result: Order status is displaying as 'Pending Payment'

Acceptance Criteria: Order status should be displayed as 'Oxipay Processed' or similar as on Magento.

Screen Cast: https://www.screencast.com/t/tAw4NcMDfqO 

Shared Document: http://docs.oxipay.com.au/platforms/magento_1/

Test Case: Verify that when payment is successful in Oxipay, order status should be 'Oxipay Processed' in admin dashboard.

Environment:
oxipay-woocommerce_v1.0.0
WordPress-4.7.4
Woocommerce-3.0.4
Country: Australia

**Comment by hellotaotao** [comment]
The question mark "?" in page URL is causing this problem. 
A temporary workaround is to change the WordPress Permalink setting to anything other than "Plain".

**Comment by blueninja2** [comment]
The issue is only occuring if the Permalinks are set to Plain as explained in more detail here: #57

**Comment by blueninja2** [comment]
We suspect this is correct behaviour and standard WooCommerce - Sam/Tao to liaise QA info tech to clarify further.
