### ISSUE TITLE
Closing browser on success page leaves order in "Pending Payment" state with no email receipt from WooCommerce (async-callback)

### ISSUE THREAD

**Issue by hellotaotao** [oxipay/oxipay-woocommerce#55]
**Steps**
1 - Checkout an item using Oxipay
2 - Proceed with payment until you get to the Oxipay success page.
3 - Close browser before redirection completes.
4 - Check the status of the order on the WordPress admin page.

**Expected**
* Order set to **Processing** 
* WordPress sends a confirmation email receipt similar to the one that Oxipay sends.

**Actual**
* No confirmation email receipt from WordPress, only from Oxipay. 
* Status of the order is set to Pending Payment.

**Tech Stack**
oxipay-woocommerce_v1.0.0
WordPress-4.7.4
Woocommerce-3.0.4
Country: Australia

**Comment**
The async callback - which was designed to prevent against scenarios where the user closes their browser on success page - is currently not implemented in WooCommerce as per the following code in the **oxipay.php** file in the plugin

		function oxipay_callback()
		{
			//todo: provide asynchronous callback implementation for increased resilience during network disruption
			throw new Exception("Not implemented");
		}

![image](https://cloud.githubusercontent.com/assets/1796860/25462354/932a8184-2b2d-11e7-86b8-93bf80b5da15.png)

Screenshot below shows the state for the order as still **Pending Payment**

![image](https://cloud.githubusercontent.com/assets/22509613/25933385/767b95ae-3655-11e7-94b0-59d67860f43b.png)

**Comment by blueninja2** [comment]
@AstralProgrammer This plugin is currently out there and currently being used. However, people have had issues with the callback mechanism. We have investigated this and found that this was happening because the callback URL was going to a php file (callback.php) that doesn't exist in the plugin.

Can you please consider this as a high priority.

**Comment by oxipay** [comment]
This has been resolved and the callback functionality implemented.
