### ISSUE TITLE
"Plain" permalinks cause successful orders not to redirect to a confirmation page and are left in Pending Payment

### ISSUE THREAD

**Issue by sam-oxipay** [oxipay/oxipay-woocommerce#57]
Steps to Replicate
---------------------
**Note**: By default, WordPress sets Permalinks to the **Day and Name** option.
1 - In the WordPress admin area, navigate to **Settings** -> **Permalinks**
2 - Select **Plain** and then click on **Save Changes** at the bottom as per screenshot below.
3 - Now select an item, select Oxipay and proceed with your payment until you are presented with a success page.

![image](https://cloud.githubusercontent.com/assets/22509613/25465406/29ae46dc-2b41-11e7-8e23-027858d4df57.png)

Expected Result
---------------------
1 - WordPress displays a thank you page confirming the order was successful.
2 - The order's state is set to **Processing** since the order was successfully approved.

Actual Result
---------------------
1 - Oxipay does not redirect the customer to a thank you page, instead taking them to the store's homepage.
2 - The order's state is set to **Pending Payment** even though it was successfully processed by Oxipay and the customer received a confirmation email from Oxipay.

Note
--------
All other permalinks setting options - namely 'Day and name', 'Month and name', 'Numeric' and 'Post name' are unaffected by this

**Comment by blueninja2** [comment]
Possibly an issue with the Oxipay application - to investigate internally before determining whether to get Terem involved in fixing it.

**Comment by am-oxipay** [comment]
This has been resolved.
