### ISSUE TITLE
[QAIT] For Automatic Installation flow Oxipay plugin fails to appear in Wordpress/woocommerce older version plugin. 

### ISSUE THREAD

**Issue by ramanjeetaulakh-qait** [oxipay/oxipay-woocommerce#58]
Steps:
1) Install WordPress
2) Launch Worpress Admin panel.
2) Install Woocommerce
3) Install Oxipay Plugin (Latest Version- v1.0.0)
4) Under Wordpress>Plugins> Installed Plugins verify Oxipay Payment Gateway plugin appears.
5) Activate the oxipay plugin
6) Navigate to WooCommerce> Settings> checkout, Scroll down to Payment gateways section.
7) Repeat step 4 to 6 for oxipay plugin version (oxipay-woocommerce_v0.4.18)

Result:
No oxipay plugin is visible even if it is activated in Wordpress>Plugins> Installed Plugins window.

Expected:
oxipay plugin should be visible.

Issue Reproducible for Automatic Installation flow on old version of WP/woocommerce. 
Same issue not reproducible for Manual Installation.
Please find below Tech-Stack details:

Ubuntu (16.04 LTS) 
PHP version:(5.6.30)
mysql: (14.14)
Apache: (2.4.18)

WordPress-4.6.5
Woocommerce-3.0.0
oxipay-woocommerce_v1.0.0
oxipay-woocommerce_0.4.18

Screen Cast: http://screencast-o-matic.com/watch/cbftjkXoxX

Issue not reproducible for latest version available in market for WP/woocommerce.
For both Automatic and Manual Installation.
Please find below Tech-Stack details:

Ubuntu (16.04 LTS) 
PHP version:(5.6.30)
mysql: (14.14)
Apache: (2.4.18)

WordPress-4.7.4
Woocommerce-3.0.4
oxipay-woocommerce_v1.0.0
oxipay-woocommerce_v0.4.18

Screen Cast: http://screencast-o-matic.com/watch/cbftjUXow7

**Comment by blueninja2** [comment]
This is downgrading of the plugin and not an issue to be fixed by Terem.
