### ISSUE TITLE
[QAIT] For an amount less than 20$ >> Status of order gets cancelled and no Pay button appears if user tries to initially pay through Oxipay.

### ISSUE THREAD

**Issue by Piyush-Qait** [oxipay/oxipay-woocommerce#60]
**Steps to Replicate:**
1. Launch the woocommerce : http://115.113.54.81/wordpress/
2. Select any product with price tag less than 15 $ e.g., http://115.113.54.81/wordpress/product/p05/?v=5ff0a18a0ee9
3. Checkout using Oxipay and verify than Oxipay restricts the user from paying an amount less than 20 $
4. Now navigate to 'Orders' tab under 'My Account'
5. Observe that status of order is appearing as 'Cancelled' instead of 'Pending payment' and no Pay button is present for this order unlike other pending orders.

NOTE: In this scenario if user has navigated to the My Accounts page directly from payment page then this is restricting the user from paying for an order less than 20$.

**Acceptance Criteria:** For an amount less than 20$: User should be able to pay through any other mode of payment if oxipay doesn't allow it to pay through itself.

Screen cast: https://www.screencast.com/t/IXG26wBMqrId

Document URL:
http://docs.oxipay.com.au/platforms/woocommerce/

Tech-Stack:
Ubuntu (16.04 LTS)
PHP version:(5.6.30)
mysql: (14.14)
Apache: (2.4.18)

WordPress-4.6.5
Woocommerce-3.0.0
oxipay-woocommerce_v1.0.0
oxipay-woocommerce_0.4.18

**Comment by blueninja2** [comment]
To do more triaging and investigation on this issue before deciding whether handing off to .Terem
