### ISSUE TITLE
[QAIT] “Day and name” / “Month and name” / “Numeric” / ”Post name” / “Custom Structure” permalinks redirects user to blank ‘Order received’ page. Also, throws 500 Internal Server Error on console

### ISSUE THREAD

**Issue by Piyush-Qait** [oxipay/oxipay-woocommerce#61]
Pre-requisite: 
Change permalinks common setting to any setting except ‘Plain’

Steps to Replicate:

1) Launch the URL: http://115.113.54.81/wordpress/?v=a6cd7f0b74bc
2) Click on shop
3) Click on any product and then click on ‘Add to Cart’
4) Click on Proceed to checkout
5) Enter your billing details
6) Select Oxipay in payment options and click on ‘Proceed to Oxipay’
7) Login with valid credentials on Oxipay
8) Enter in card details and click on ‘Confirm’ button
9) Verify the result on wordpress

Actual Result: Oxipay redirects user to blank ‘Order received’ page and does not display any thank you message or order invoice

Acceptance Criteria: WordPress should display a thank you page and order invoice confirming the order was successful

Observation: Order status for all above permalinks options are ‘Processing’ which is correct.

Screencast: https://www.screencast.com/t/Aea2SEvRK7z

Shared Document: http://docs.oxipay.com.au/platforms/magento_1/

Tech-Stack:
Ubuntu (16.04 LTS)
PHP version:(5.6.30)
mysql: (14.14)
Apache: (2.4.18)
WordPress-4.6.5
Woocommerce-3.0.0
oxipay-woocommerce_v1.0.0
oxipay-woocommerce_0.4.18

**Comment by blueninja2** [comment]
To do more impact analysis in relation to this issue before deciding whether to send off to Terem.
