### ISSUE TITLE
[QAIT] NZ Oxipay> Payment gets declined with Oxipay when payment amount is greater than $20 and less than $100

### ISSUE THREAD

**Issue by Piyush-Qait** [oxipay/oxipay-woocommerce#62]
Pre-requisite: Configure NZ Oxipay gateway

Merchant ID: 30199262
API Key: E6894550-BEB3-446E-916B-2A4AA6600E2F
Gateway: https://securesandbox.oxipay.co.nz/Checkout?platform=Default
Oxipay Region: NZ
Base Location as - NZ
Currency: New Zealand dollar

Steps to Replicate:

1) Launch the URL: http://115.113.54.81/wordpress/?v=a6cd7f0b74bc
2) Click on shop
3) Select any product with price tag less than 100 and then click on ‘Add to Cart’
4) Click on Proceed to checkout
5) Enter your billing details
6) Select Oxipay in payment options and click on ‘Proceed to Oxipay’
7) Login with valid credentials on Oxipay
8) Verify the result

Actual Result: Payment gets declined with Oxipay when payment amount is greater than $20 and less than $100

Acceptance Criteria: Payment should be approved when the payment amount is greater than $20 regardless of AU or NZ gateway. 

Observation: for AU gateway, it approves all the payments which are greater than $20

Screencast: https://www.screencast.com/t/9ECgYXhsbR 

Shared Document: http://docs.oxipay.com.au/platforms/magento_1/

Tech-Stack:
Ubuntu (16.04 LTS)
PHP version:(5.6.30)
mysql: (14.14)
Apache: (2.4.18)
WordPress-4.6.5
Woocommerce-3.0.0
oxipay-woocommerce_v1.0.0
oxipay-woocommerce_0.4.18

**Comment by blueninja2** [comment]
This is not likely an issue with the plugin itself.
