### ISSUE TITLE
Plugin hijacks other payment methods

### ISSUE THREAD

**Issue by CheribombRetro** [oxipay/oxipay-woocommerce#69]
I have paypal, oxipay, afterpay, zippay all set as payment methods on my site. (woocommerce)

Since activatoin of oxipay, it hijacks and declines afterpay and zippay payments with the following message, but the user actually successfully paid by afterpay. I received a declined message and she received nothing from the site, though she did receive a successful order placement from afterpay. I'm all for helping you guys grow bigger in market, but i can't do it at the cost of orders. I've deactivated OP plug in until this is fixed.

*Oxipay payment response failed signature validation. Please check your Merchant Number and API key or contact Oxipay for assistance.*

![image](https://cloud.githubusercontent.com/assets/28912441/26383653/6141b994-4077-11e7-9543-d46a7b75dd5e.png)

**Comment by blueninja2** [comment]
Hi,
Thanks for the report.
We are aware of the issue and should have a new release out today to address it.
Thanks,

**Comment by oxipay** [comment]
This has been resolved.
