### ISSUE TITLE
New Plugin Denies other payment methods

### ISSUE THREAD

**Issue by CheribombRetro** [oxipay/oxipay-woocommerce#73]
Hi there

Thansk for the new plug in - now we are unable to process any afterpay at all! 

(windows, chrome v 58.0)

![image](https://cloud.githubusercontent.com/assets/28912441/26432179/3a989da0-413d-11e7-9124-aaaf6028a3f8.png)

I've had to deactivate oxipay again for now.

best
Cheridan

**Comment by am-oxipay** [comment]
Hi,
The change in the v1.0.1 version of the plugin simply checks the order to ensure that it is an oxipay transaction. If it is not then we simply return the orderId as required so this should have no effect on any other plugin or any transaction that is not an oxipay transaction. 

Do you have any additional information that you could provide (logs etc.. ) which would indicate that the oxipay plugin is behaving incorrectly ?

Please feel free to contact the platform integration team directly and we can work with you on your specific environment as we have merchants that have other payment gateway plugins, including the one you mentioned, which are able to co-exist. 

Please contact: pit@oxipay.com.au +08 8464 1835
